server:
  port: 8080

spring:
  application:
    name: ProofForge API

  datasource:
    url: jdbc:h2:mem:proofforge_dev_db
    driver-class-name: org.h2.Driver
    username: sa
    password:

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID:google-dev-client-id}
            client-secret: ${GOOGLE_CLIENT_SECRET:google-dev-client-secret}
            scope:
              - openid
              - profile
              - email
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"

          github:
            client-id: ${GITHUB_CLIENT_ID:github-dev-client-id}
            client-secret: ${GITHUB_CLIENT_SECRET:github-dev-client-secret}
            scope:
              - read:user
              - user:email
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"

proofforge:
  app:
    name: ProofForge API
    version: 0.4.0
    phase: phase-04-authentication

  frontend-url: ${PF_FRONTEND_URL:http://localhost:5173}

  cors:
    allowed-origins: ${PF_CORS_ALLOWED_ORIGINS:http://localhost:5173}

  security:
    jwt:
      secret: ${PF_JWT_SECRET:proof-forge-development-secret-must-be-at-least-sixty-four-characters-long-change-me}
      expiration-minutes: ${PF_JWT_EXPIRATION_MINUTES:1440}